services:
  - type: web
    name: ia-estimador
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -k gthread -w 1 --threads 1 -t 300 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: HF_HOME
        value: /var/data/hf_cache

