
services:
  - type: web
    name: ia-estimador
    env: python
    buildCommand: |
      pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn -k gthread -w 1 --threads 1 -t 300 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: HF_HOME
        value: /var/data/hf_cache
      - key: LAZY_BOOT
        value: "1"
      - key: EMB_MODEL
        value: sentence-transformers/paraphrase-MiniLM-L3-v2
      - key: MAX_SEQ_LEN
        value: "256"
      - key: EMB_BATCH
        value: "8"
      - key: OMP_NUM_THREADS
        value: "1"
      - key: MKL_NUM_THREADS
        value: "1"
      - key: NUMEXPR_NUM_THREADS
        value: "1"
      - key: TOKENIZERS_PARALLELISM
        value: "false"
      - key: FAISS_NUM_THREADS
        value: "1"
      - key: WEB_CONCURRENCY
        value: "1"
